### ISSUE TITLE
Errors in VS 15 Preview 3

### ISSUE THREAD

**Issue by zooba** [NuGet/NuGet.PackageIndex#16]
Not sure this is the right place, but it was easiest to find.

I'm seeing this error in the ActivityLog.xml and a "failed to load extension" dialog box occasionally in VS 15 Preview 3:

```
CreateInstance failed for package [NuGetPackage]Source: 'mscorlib' Description: Exception has been thrown by the target of an invocation. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Runtime.InteropServices.COMException: InitializePackageServiceProvider must be called on the UI thread.
 at Microsoft.VisualStudio.Shell.ThreadHelper.ThrowIfNotOnUIThread(String callerMemberName)
 at NuGet.PackageManagement.VisualStudio.ServiceLocator.InitializePackageServiceProvider(IServiceProvider provider)
 at NuGetVSExtension.NuGetPackage..ctor() --- End of inner exception stack trace ---
 at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
 at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
 at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
 at System.Activator.CreateInstance(Type type, Boolean nonPublic)
 at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
 at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
 at System.Activator.CreateInstance(String assemblyString, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo, StackCrawlMark& stackMark)
 at System.Activator.CreateInstance(String assemblyName, String typeName)
 at System.AppDomain.CreateInstance(String assemblyName, String typeName)System.Runtime.InteropServices.COMException (0x8001010E): InitializePackageServiceProvider must be called on the UI thread.
 at Microsoft.VisualStudio.Shell.ThreadHelper.ThrowIfNotOnUIThread(String callerMemberName)
 at NuGet.PackageManagement.VisualStudio.ServiceLocator.InitializePackageServiceProvider(IServiceProvider provider)
 at NuGetVSExtension.NuGetPackage..ctor()
```

It's seemingly random, but I wasn't deliberately trying to use Nuget at all - it just appeared.

**Comment by drewgillies** [comment]
Moved to https://github.com/NuGet/Home/issues/3073
